In [15]:
import sys 
import numpy as np
import pandas as pd
import sklearn

print("python version:", sys.version)
print("numpy version:", np.__version__)
print("pandas version:", pd.__version__)
print("sklearn version:", sklearn.__version__)

python version: 3.14.3 (tags/v3.14.3:323c59a, Feb  3 2026, 16:04:56) [MSC v.1944 64 bit (AMD64)]
numpy version: 2.4.2
pandas version: 3.0.1
sklearn version: 1.8.0


In [18]:
np.random.seed(100)
matr = np.random.random((100, 5))

print("shape:", matr.shape)
print("dtype:", matr.dtype)
print("first 5 rows:\n", matr[0:5])

shape: (100, 5)
dtype: float64
first 5 rows:
 [[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
 [0.12156912 0.67074908 0.82585276 0.13670659 0.57509333]
 [0.89132195 0.20920212 0.18532822 0.10837689 0.21969749]
 [0.97862378 0.81168315 0.17194101 0.81622475 0.27407375]
 [0.43170418 0.94002982 0.81764938 0.33611195 0.17541045]]


In [17]:
print("avg:", np.mean(matr))
print("std:", np.std(matr))
print("min:", np.min(matr))
print("max:", np.max(matr))
print("avg (axis=0):", np.mean(matr, axis=0))
print("std (axis=0):", np.std(matr, axis=0))
print("min (axis=0):", np.min(matr, axis=0))
print("max (axis=0):", np.max(matr, axis=0))

avg: 0.49510358589115017
std: 0.29289352190390705
min: 0.0004867594752598903
max: 0.998932268843212
avg (axis=0): [0.48398045 0.53750043 0.49495914 0.47617655 0.48290136]
std (axis=0): [0.30809976 0.26459935 0.28174881 0.31854874 0.28409635]
min (axis=0): [0.00993369 0.00568851 0.00048676 0.00139902 0.00471886]
max (axis=0): [0.99219069 0.99893227 0.9908928  0.99264224 0.99345358]


In [19]:
w = np.random.random((5))
y = matr @ w
print("y.shape:", y.shape)

y.shape: (100,)


In [23]:
w_true = np.array([1, 2, 3, 4, 5])
noise = np.random.random((100)) * 0.1
y_true = matr @ w_true + noise

w_guess = w_true + np.random.random((5)) * 0.5 - 0.25
y_pred = matr @ w_guess

mse = np.mean((y_true - y_pred) ** 2)
print("MSE:", mse)
mae = np.mean(np.abs(y_true - y_pred))
print("MAE:", mae)
rmse = np.sqrt(mse)
print("RMSE:", rmse)
r2 = 1 - np.sum((y_true - y_pred) ** 2) / np.sum((y_true - np.mean(y_true)) ** 2)
print("R^2:", r2)


MSE: 0.02911580736606204
MAE: 0.14477880094318016
RMSE: 0.17063354701248531
R^2: 0.9940427018575441
